#!/usr/bin/env python3
"""Convert a trained ternary transformer (model_int8.npz from train.py) to a
C/C++ header file consumed by ColorClassifier/classifier.h."""

import argparse
import os

import numpy as np


def fmt_float(x):
    s = f"{float(x):.8g}"
    # `0` and integer-like strings become invalid float literals when we
    # append the `f` suffix (e.g. `0f` is parsed as octal). Force a decimal.
    if "." not in s and "e" not in s and "E" not in s:
        s += ".0"
    return s + "f"


def emit_array(name, arr, *, c_type, formatter):
    flat = arr.flatten()
    parts = [formatter(v) for v in flat]
    rows = []
    for i in range(0, len(parts), 8):
        rows.append("  " + ", ".join(parts[i : i + 8]))
    body = ",\n".join(rows)
    return f"const {c_type} {name}[{len(flat)}] = {{\n{body}\n}};"


def emit_float(name, arr):
    return emit_array(name, arr, c_type="float", formatter=fmt_float)


def emit_int8(name, arr):
    return emit_array(name, arr.astype(np.int8), c_type="int8_t", formatter=lambda v: str(int(v)))


def main():
    here = os.path.dirname(os.path.abspath(__file__))
    repo = os.path.abspath(os.path.join(here, ".."))
    default_out = [
        os.path.join(here, "ColorClassifier", "model_weights.h"),
        os.path.join(repo, "Arduino Code", "P.A.R.Main", "model_weights.h"),
        os.path.join(repo, "Arduino Code", "ColorSensorTest", "model_weights.h"),
    ]
    ap = argparse.ArgumentParser()
    ap.add_argument("--in", dest="in_npz", default=os.path.join(here, "model_int8.npz"))
    ap.add_argument(
        "--out",
        action="append",
        help="output header path (repeat to write multiple copies). "
             "Defaults to ColorClassifier/, P.A.R.Main/, ColorSensorTest/.",
    )
    args = ap.parse_args()

    if not args.out:
        args.out = default_out

    z = np.load(args.in_npz)
    n_tokens, d_model = z["tok_proj"].shape
    d_ff = z["ff1_w_int"].shape[0]

    out = []
    out.append("// Auto-generated by export_header.py — do not edit by hand.")
    out.append("// Tiny ternary transformer weights for blue/black RGBC classification.")
    out.append("#pragma once")
    out.append("#include <stdint.h>")
    out.append("")
    out.append(f"#define MODEL_N_TOKENS {n_tokens}")
    out.append(f"#define MODEL_D_MODEL  {d_model}")
    out.append(f"#define MODEL_D_FF     {d_ff}")
    out.append("")

    out.append(emit_float("INPUT_MEAN", z["input_mean"]))
    out.append(emit_float("INPUT_STD", z["input_std"]))
    out.append("")

    out.append(emit_float("TOK_PROJ", z["tok_proj"]))
    out.append(emit_float("TOK_BIAS", z["tok_bias"]))
    out.append("")

    for ln in ("ln1", "ln2", "ln_out"):
        out.append(emit_float(f"{ln.upper()}_W", z[f"{ln}_w"]))
        out.append(emit_float(f"{ln.upper()}_B", z[f"{ln}_b"]))
    out.append("")

    for name in ("q", "k", "v", "o", "ff1", "ff2", "head"):
        out.append(emit_int8(f"{name.upper()}_W", z[f"{name}_w_int"]))
        out.append(f"const float {name.upper()}_ALPHA = {fmt_float(z[f'{name}_alpha'])};")
        bkey = f"{name}_b"
        if bkey in z.files:
            out.append(emit_float(f"{name.upper()}_B", z[bkey]))
        out.append("")

    body = "\n".join(out)
    for path in args.out:
        os.makedirs(os.path.dirname(path), exist_ok=True)
        with open(path, "w") as f:
            f.write(body)
        print(f"wrote {path}")
    print(f"  (d_model={d_model}, d_ff={d_ff}, n_tokens={n_tokens})")


if __name__ == "__main__":
    main()
