#!/bin/bash
# Launch setup_youtube_auth.py in the GUI session's Terminal.app.
#
# WHY (same two reasons as run_backfill.sh): an SSH shell cannot unlock the
# login Keychain that holds the vault passphrase (`security find-generic-password`
# returns rc=36 there), and the OAuth consent flow needs a browser plus the
# loopback redirect. Terminal.app runs in the console user's session and can do
# both; `open -a Terminal <file>` reaches it from SSH. Args are baked into a
# generated .command because `open` cannot pass argv through.
#
# The script is INTERACTIVE — it asks you to confirm each channel before it
# writes anything — so watch the Terminal window it opens (or the screen share).
#
# Usage:  ./run_auth_setup.sh --show                  # which channel is each token on?
#         ./run_auth_setup.sh                         # consent both, upload then playlist
#         ./run_auth_setup.sh --which playlist
#         ./run_auth_setup.sh --expect-upload-handle @PixelArtRobot
set -euo pipefail
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
LOGDIR=/tmp/par-record
mkdir -p "$LOGDIR"
STAMP="$(date +%Y%m%d-%H%M%S)"
CMDFILE="$LOGDIR/ytauth-$STAMP.command"
LOGFILE="$LOGDIR/ytauth-$STAMP.log"

# Guard the zero-arg case: `printf '%q ' "$@"` with no args still runs the
# format once and emits a literal '', which argparse rejects.
ARGS=""
if [ "$#" -gt 0 ]; then
  ARGS="$(printf '%q ' "$@")"
fi

cat > "$CMDFILE" <<EOF
#!/bin/bash
# Generated by run_auth_setup.sh — runs under Terminal.app for Keychain + browser.
cd '$HERE'
./venv/bin/python setup_youtube_auth.py $ARGS 2>&1 | tee '$LOGFILE'
echo
echo "=== auth setup finished (exit \${PIPESTATUS[0]}) — log: $LOGFILE ==="
EOF
chmod +x "$CMDFILE"

open -a Terminal "$CMDFILE"
echo "launched in the GUI session's Terminal.app:"
echo "  ./venv/bin/python setup_youtube_auth.py $ARGS"
echo "it is INTERACTIVE — answer the prompts in that window."
echo "follow it from here with:  tail -f $LOGFILE"
