#!/bin/bash
# Launch record_clip.py in the GUI session's Terminal.app — the only way to get a
# camera grant when you're driving this over SSH.
#
# WHY: macOS camera (TCC) grants are keyed to app BUNDLES. An SSH shell has no
# promptable bundle identity, so record_clip.py reads NotDetermined, the consent
# prompt never appears, and a capture started anyway streams ZERO frames — a
# silently empty file (the failure documented in the yt-streamer-camera-tcc
# notes). Terminal.app already holds a camera grant on this Mac, and a process it
# spawns inherits it as its responsible process.
#
# `open -a Terminal <file>` hands the file to LaunchServices, which runs it in the
# console user's GUI session — this works from SSH (unlike a bare osascript, whose
# AppleEvents can't cross into the GUI bootstrap namespace). The args are baked
# into a generated .command because `open` cannot pass argv through.
#
# The recording outlives this shell and the Terminal window it opens.
#
# Usage:  ./run_record_clip.sh --minutes 50 --out ~/Documents
set -euo pipefail
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
LOGDIR=/tmp/par-record
mkdir -p "$LOGDIR"
CMDFILE="$LOGDIR/launch-$(date +%Y%m%d-%H%M%S).command"

# Re-quote each arg so ones containing spaces (--camera 'Brio 100') survive the
# round-trip through the generated file.
ARGS="$(printf '%q ' "$@")"

cat > "$CMDFILE" <<EOF
#!/bin/bash
# Generated by run_record_clip.sh — runs under Terminal.app for the camera grant.
cd '$HERE'
exec caffeinate -i ./venv/bin/python record_clip.py $ARGS
EOF
chmod +x "$CMDFILE"

open -a Terminal "$CMDFILE"
echo "launched in the GUI session's Terminal.app:"
echo "  ./venv/bin/python record_clip.py $ARGS"
echo "progress log: $LOGDIR/<name>.log   (tail -f $LOGDIR/brio-*.log)"
