#!/bin/bash
# Launch backfill_uploads.py in the GUI session's Terminal.app.
#
# WHY: two things this script needs are unreachable from an SSH shell.
#   1. The vault passphrase lives in the login Keychain, which an SSH session
#      cannot unlock — `security find-generic-password` returns rc=36 there, so
#      _vault_get_password() raises and the client secrets never load.
#   2. The OAuth consent flow has to open a browser and take the loopback
#      redirect. That is a GUI-session affair.
# Terminal.app runs in the console user's session and can do both, and
# `open -a Terminal <file>` reaches it from SSH (a bare osascript cannot cross
# into the GUI bootstrap namespace). Args are baked into a generated .command
# because `open` cannot pass argv through — same trick as run_record_clip.sh.
#
# Usage:  ./run_backfill.sh                 # re-auth if needed, upload orphans
#         ./run_backfill.sh --dry-run
#         ./run_backfill.sh --force-reauth
set -euo pipefail
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
LOGDIR=/tmp/par-record
mkdir -p "$LOGDIR"
STAMP="$(date +%Y%m%d-%H%M%S)"
CMDFILE="$LOGDIR/backfill-$STAMP.command"
LOGFILE="$LOGDIR/backfill-$STAMP.log"

# Guard the zero-arg case: `printf '%q ' "$@"` with no args still runs the
# format once and emits a literal '' , which argparse then rejects as an
# unrecognised empty argument.
ARGS=""
if [ "$#" -gt 0 ]; then
  ARGS="$(printf '%q ' "$@")"
fi

cat > "$CMDFILE" <<EOF
#!/bin/bash
# Generated by run_backfill.sh — runs under Terminal.app for Keychain + browser.
cd '$HERE'
# caffeinate: a multi-GB upload must not be cut short by idle sleep.
caffeinate -i ./venv/bin/python backfill_uploads.py $ARGS 2>&1 | tee '$LOGFILE'
echo
echo "=== backfill finished (exit \${PIPESTATUS[0]}) — log: $LOGFILE ==="
EOF
chmod +x "$CMDFILE"

open -a Terminal "$CMDFILE"
echo "launched in the GUI session's Terminal.app:"
echo "  ./venv/bin/python backfill_uploads.py $ARGS"
echo "follow it from here with:  tail -f $LOGFILE"
