#!/bin/bash
# Launch migrate_channel.py in the GUI session's Terminal.app.
#
# WHY (same two reasons as run_backfill.sh):
#   1. The vault passphrase lives in the login Keychain, which an SSH session
#      cannot unlock (`security find-generic-password` -> rc=36 there).
#   2. If the upload token needs (re-)consent, the OAuth flow must open a
#      browser and take the loopback redirect — a GUI-session affair.
# `open -a Terminal <file>` reaches the console user's session from SSH; args
# are baked into a generated .command because `open` can't pass argv through.
#
# Usage:  ./run_migrate.sh --dry-run          # list what it would do
#         ./run_migrate.sh                     # re-upload all to @PixelArtRobot
#         ./run_migrate.sh --limit 1           # one video, end to end
set -euo pipefail
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
LOGDIR=/tmp/par-record
mkdir -p "$LOGDIR"
STAMP="$(date +%Y%m%d-%H%M%S)"
CMDFILE="$LOGDIR/migrate-$STAMP.command"
LOGFILE="$LOGDIR/migrate-$STAMP.log"

ARGS=""
if [ "$#" -gt 0 ]; then
  ARGS="$(printf '%q ' "$@")"
fi

cat > "$CMDFILE" <<EOF
#!/bin/bash
# Generated by run_migrate.sh — runs under Terminal.app for Keychain + browser.
cd '$HERE'
# caffeinate: many multi-GB uploads must not be cut short by idle sleep.
caffeinate -i ./venv/bin/python migrate_channel.py $ARGS 2>&1 | tee '$LOGFILE'
echo
echo "=== migrate finished (exit \${PIPESTATUS[0]}) — log: $LOGFILE ==="
EOF
chmod +x "$CMDFILE"

open -a Terminal "$CMDFILE"
echo "launched in the GUI session's Terminal.app:"
echo "  ./venv/bin/python migrate_channel.py $ARGS"
echo "follow it from here with:  tail -f $LOGFILE"
